# Generated by Django 3.1 on 2021-03-20 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('hospitalName', models.CharField(max_length=50)),
                ('hospitalID', models.AutoField(primary_key=True, serialize=False)),
                ('hospitalAddress', models.CharField(max_length=200)),
                ('bedsOccupied', models.IntegerField()),
                ('totalBeds', models.IntegerField()),
                ('hospitalPassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientName', models.CharField(max_length=50)),
                ('patientID', models.AutoField(primary_key=True, serialize=False)),
                ('lastChecked', models.DateTimeField()),
                ('bpHigh', models.IntegerField()),
                ('bpLow', models.IntegerField()),
                ('sugar', models.IntegerField()),
                ('heartRate', models.IntegerField()),
                ('oxygenRate', models.IntegerField()),
                ('tability', models.BooleanField()),
                ('hospitalID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalAvailability.hospitals')),
            ],
        ),
        migrations.AddField(
            model_name='hospitals',
            name='hospitalState',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalAvailability.state'),
        ),
    ]
