# Generated by Django 3.1 on 2021-03-20 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAvailability', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='tability',
            new_name='stability',
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastChecked',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
