# Generated by Django 3.1 on 2021-03-20 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalAvailability', '0002_auto_20210320_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitals',
            name='numberOfVaccines',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='vaccinationAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doseNo', models.IntegerField()),
                ('firstAppointmentDate', models.DateField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalAvailability.hospitals')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalAvailability.patient')),
            ],
        ),
    ]
